### PR TITLE
Update upgrading.html

### PR DESCRIPTION
**Pull request by zengxinhui**
fix typo

### CODE REVIEW

**Comment by yogthos** [comment]
thanks!

**Comment by nikolap** [comment]
Heads up this should be updated in the markdown https://github.com/kit-clj/kit-clj.github.io/blob/master/resources/md/upgrading.md, the html files are generated from that

**Comment by zengxinhui** [comment]
Ah that's why. Thank you.

**Comment by nikolap** [comment]
No worries thank you for the fix! I’ll merge when at the comp

**Pull request merged**
